/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/componentshowcase`; params?: Router.UnknownInputParams; } | { pathname: `/CustomDrawerContent`; params?: Router.UnknownInputParams; } | { pathname: `/explore`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/spotlogin`; params?: Router.UnknownInputParams; } | { pathname: `/spotplaylist`; params?: Router.UnknownInputParams; } | { pathname: `/spotsign`; params?: Router.UnknownInputParams; } | { pathname: `/Profile`; params?: Router.UnknownInputParams; } | { pathname: `/EditProfile`; params?: Router.UnknownInputParams; } | { pathname: `/../store/userSlice`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/componentshowcase`; params?: Router.UnknownOutputParams; } | { pathname: `/CustomDrawerContent`; params?: Router.UnknownOutputParams; } | { pathname: `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/spotlogin`; params?: Router.UnknownOutputParams; } | { pathname: `/spotplaylist`; params?: Router.UnknownOutputParams; } | { pathname: `/spotsign`; params?: Router.UnknownOutputParams; } | { pathname: `/Profile`; params?: Router.UnknownOutputParams; } | { pathname: `/EditProfile`; params?: Router.UnknownOutputParams; } | { pathname: `/../store/userSlice`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/componentshowcase${`?${string}` | `#${string}` | ''}` | `/CustomDrawerContent${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/spotlogin${`?${string}` | `#${string}` | ''}` | `/spotplaylist${`?${string}` | `#${string}` | ''}` | `/spotsign${`?${string}` | `#${string}` | ''}` | `/Profile${`?${string}` | `#${string}` | ''}` | `/EditProfile${`?${string}` | `#${string}` | ''}` | `/../store/userSlice${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/componentshowcase`; params?: Router.UnknownInputParams; } | { pathname: `/CustomDrawerContent`; params?: Router.UnknownInputParams; } | { pathname: `/explore`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/spotlogin`; params?: Router.UnknownInputParams; } | { pathname: `/spotplaylist`; params?: Router.UnknownInputParams; } | { pathname: `/spotsign`; params?: Router.UnknownInputParams; } | { pathname: `/Profile`; params?: Router.UnknownInputParams; } | { pathname: `/EditProfile`; params?: Router.UnknownInputParams; } | { pathname: `/../store/userSlice`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
